# Generated by Django 5.0.6 on 2025-05-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logintohome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
