# Generated by Django 5.0.6 on 2025-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logintohome', '0002_customuser_is_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
