# Generated by Django 5.0.6 on 2024-08-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couponmanagement', '0008_remove_coupon_discount_percentage'),
        ('logintohome', '0001_initial'),
        ('products', '0006_newproducts_offer'),
        ('userprofile', '0004_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('payment_method', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponmanagement.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.newproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('product_qty', models.PositiveIntegerField()),
                ('product_size', models.CharField(max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.useraddress')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newcart.allorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.newproducts')),
            ],
        ),
    ]
