# Generated by Django 5.0.6 on 2024-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allorder',
            name='coupon',
        ),
        migrations.AddField(
            model_name='mycart',
            name='coupon',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
