# Generated by Django 5.0.6 on 2024-08-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0003_alter_mycart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='coupon',
            field=models.IntegerField(default=1),
        ),
    ]
