# Generated by Django 5.0.6 on 2024-08-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0009_alter_couponusage_coupon'),
        ('newcart', '0004_alter_mycart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='couponmanagement.coupon'),
        ),
    ]
