# Generated by Django 5.0.6 on 2024-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcart', '0006_allorder_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_item',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
