# Generated by Django 5.0.6 on 2024-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_useraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_Email',
            field=models.EmailField(max_length=254),
        ),
    ]
