# Generated by Django 5.0.6 on 2024-07-29 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logintohome', '0001_initial'),
        ('userprofile', '0003_alter_useraddress_address_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('is_credit', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser')),
            ],
        ),
    ]
