# Generated by Django 5.0.6 on 2024-07-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
