# Generated by Django 5.0.6 on 2024-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0002_alter_coupon_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
