# Generated by Django 5.0.6 on 2024-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0003_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='critiria_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
