# Generated by Django 5.0.6 on 2024-07-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0004_coupon_critiria_amount'),
        ('logintohome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponmanagement.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser')),
            ],
        ),
    ]
