# Generated by Django 5.0.6 on 2024-07-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0005_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
