# Generated by Django 5.0.6 on 2024-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0006_coupon_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
