# Generated by Django 5.0.6 on 2024-07-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couponmanagement', '0007_alter_coupon_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percentage',
        ),
    ]
