# Generated by Django 5.0.6 on 2024-07-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycart',
            old_name='prod_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='mycart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='mycart',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
