# Generated by Django 5.0.6 on 2024-07-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_rename_prod_id_mycart_product_and_more'),
        ('logintohome', '0001_initial'),
        ('products', '0005_delete_varients'),
        ('userprofile', '0002_useraddress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField()),
                ('payment_method', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('return_status', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amt', models.DecimalField(decimal_places=1, default=0, max_digits=30)),
                ('product_qty', models.PositiveIntegerField()),
                ('product_price', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.useraddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.newproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logintohome.customuser')),
            ],
        ),
    ]
