# Generated by Django 5.0.6 on 2024-07-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='discount_amt',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='return_status',
        ),
    ]
