# Generated by Django 5.0.6 on 2024-07-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_remove_orders_discount_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_size',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
