# Generated by Django 5.0.6 on 2024-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_orders_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount_amt',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30),
        ),
    ]
