# Generated by Django 5.0.6 on 2024-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_orders_discount_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
