# Generated by Django 5.0.6 on 2024-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='large',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newproducts',
            name='medium',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newproducts',
            name='small',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='varients',
        ),
    ]
