# Generated by Django 5.0.6 on 2024-07-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_varients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='varients',
        ),
    ]
